AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an S3 bucket with versioning enabled

Parameters:
  BucketName:
    Type: String
    # Default: placeholder-value
    Description: Name of S3 Bucket

# Conditions:
#   BucketNameGiven: !Not
      # - !Equals 
      #   - !Ref BucketName
      #   - placeholder-value

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: #!If
        # - BucketNameGiven
        !Ref BucketName
        # - !Sub ${AWS::StackId}-lamp
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: expire-old-versions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
            ExpiredObjectDeleteMarker: true

Outputs:
  S3BucketName:
    Description: The bucket name of the versioned S3 bucket created
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${AWS::StackName}-S3BucketName
  S3BucketArn:
    Description: The ARN of the versioned S3 bucket created
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: !Sub ${AWS::StackName}-S3BucketArn